[build.environment]
  NETLIFY_USE_PNPM = "true"
  NODE_VERSION = "16"

[build]
  publish = "docs/.vitepress/dist"
  command = "pnpm install && pnpm -w run deploy"

[[redirects]]
  from = "/play/*"
  to = "/play/index.html"
  status = 200  

[functions]
  node_bundler = "esbuild"
